import time

import allure
import pytest_check as check
from locators.locators_list_of_cars import ListCarsMainPageElements
from conftest import web_browser

@allure.story('Тест главной страницы "av.by"')
@allure.feature('Проверка хедера')
def test_list_of_cars(web_browser):
    """ Этот тест проверяет кликабельность элементов всех машин, их наличие и корректность переходов по ссылкам """

    page = ListCarsMainPageElements(web_browser)

    page.btn_all_stamps.click()
    time.sleep(1)

    cars_list = [(page.btn_list_cars_abarth, 'https://cars.av.by/abarth'),
                 (page.btn_list_cars_acura, 'https://cars.av.by/acura'),
                 (page.btn_list_cars_aito, 'https://cars.av.by/aito'),
                 (page.btn_list_cars_alfa_romeo, 'https://cars.av.by/alfa-romeo'),
                 (page.btn_list_cars_alpina, 'https://cars.av.by/alpina'),
                 (page.btn_list_cars_audi, 'https://cars.av.by/audi'),
                 (page.btn_list_cars_avatr, 'https://cars.av.by/avart'),
                 (page.btn_list_cars_baic, 'https://cars.av.by/baic'),
                 (page.btn_list_cars_baojun, 'https://cars.av.by/baojun'),
                 (page.btn_list_cars_baw, 'https://cars.av.by/baw'),
                 (page.btn_list_cars_belgee, 'https://cars.av.by/belgee'),
                 (page.btn_list_cars_bentley, 'https://cars.av.by/bentley'),
                 (page.btn_list_cars_bmw, 'https://cars.av.by/bmw'),
                 (page.btn_list_cars_brilliance, 'https://cars.av.by/brilliance'),
                 (page.btn_list_cars_buick, 'https://cars.av.by/buick'),
                 (page.btn_list_cars_byd, 'https://cars.av.by/byd'),
                 (page.btn_list_cars_cadillac, 'https://cars.av.by/cadillac'),
                 (page.btn_list_cars_changan, 'https://cars.av.by/changan'),
                 (page.btn_list_cars_chery, 'https://cars.av.by/chery'),
                 (page.btn_list_cars_chevrolet, 'https://cars.av.by/chevrolet'),
                 (page.btn_list_cars_chrysler, 'https://cars.av.by/chrysler'),
                 (page.btn_list_cars_citroen, 'https://cars.av.by/citroen'),
                 (page.btn_list_cars_cupra, 'https://cars.av.by/cupra'),
                 (page.btn_list_cars_dacia, 'https://cars.av.by/dacia'),
                 (page.btn_list_cars_daewoo, 'https://cars.av.by/daewoo'),
                 (page.btn_list_cars_daihatsu, 'https://cars.av.by/daihatsu'),
                 (page.btn_list_cars_datsun, 'https://cars.av.by/datsun'),
                 (page.btn_list_cars_dayun, 'https://cars.av.by/dayun'),
                 (page.btn_list_cars_denza, 'https://cars.av.by/denza'),
                 (page.btn_list_cars_dodge, 'https://cars.av.by/dodge'),
                 (page.btn_list_cars_dongfeng, 'https://cars.av.by/dong-feng'),
                 (page.btn_list_cars_dongfeng_honda, 'https://cars.av.by/dongfeng-honda'),
                 (page.btn_list_cars_dc, 'https://cars.av.by/ds'),
                 (page.btn_list_cars_exeed, 'https://cars.av.by/exeed'),
                 (page.btn_list_cars_farizon, 'https://cars.av.by/farizon'),
                 (page.btn_list_cars_faw, 'https://cars.av.by/faw'),
                 (page.btn_list_cars_ferrari, 'https://cars.av.by/ferrari'),
                 (page.btn_list_cars_fiat, 'https://cars.av.by/fiat'),
                 (page.btn_list_cars_ford, 'https://cars.av.by/ford'),
                 (page.btn_list_cars_foton, 'https://cars.av.by/foton'),
                 (page.btn_list_cars_gac, 'https://cars.av.by/gac'),
                 (page.btn_list_cars_geely, 'https://cars.av.by/geely'),
                 (page.btn_list_cars_genesis, 'https://cars.av.by/genesis'),
                 (page.btn_list_cars_gmc, 'https://cars.av.by/gmc'),
                 (page.btn_list_cars_great_wall, 'https://cars.av.by/great-wall'),
                 (page.btn_list_cars_hafei, 'https://cars.av.by/hafei'),
                 (page.btn_list_cars_haima, 'https://cars.av.by/haima'),
                 (page.btn_list_cars_haval, 'https://cars.av.by/haval'),
                 (page.btn_list_cars_hiphi, 'https://cars.av.by/hiphi'),
                 (page.btn_list_cars_honda, 'https://cars.av.by/honda'),
                 (page.btn_list_cars_hongqi, 'https://cars.av.by/hongqi'),
                 (page.btn_list_cars_hozon, 'https://cars.av.by/hozon'),
                 (page.btn_list_cars_hummer, 'https://cars.av.by/hummer'),
                 (page.btn_list_cars_hyundai, 'https://cars.av.by/hyundai'),
                 (page.btn_list_cars_infiniti, 'https://cars.av.by/infiniti'),
                 (page.btn_list_cars_khodro, 'https://cars.av.by/iran-khodro'),
                 (page.btn_list_cars_isuzu, 'https://cars.av.by/isuzu'),
                 (page.btn_list_cars_jac, 'https://cars.av.by/jac'),
                 (page.btn_list_cars_jaguar, 'https://cars.av.by/jaguar'),
                 (page.btn_list_cars_jeep, 'https://cars.av.by/jeep'),
                 (page.btn_list_cars_jetour, 'https://cars.av.by/jetour'),
                 (page.btn_list_cars_jetta, 'https://cars.av.by/jetta'),
                 (page.btn_list_cars_jiyue, 'https://cars.av.by/jiyue'),
                 (page.btn_list_cars_jmev, 'https://cars.av.by/jmev'),
                 (page.btn_list_cars_kaiyi, 'https://cars.av.by/kaiyi'),
                 (page.btn_list_cars_kia, 'https://cars.av.by/kia'),
                 (page.btn_list_cars_lada, 'https://cars.av.by/lada-vaz'),
                 (page.btn_list_cars_lancia, 'https://cars.av.by/lancia'),
                 (page.btn_list_cars_rover, 'https://cars.av.by/land-rover'),
                 (page.btn_list_cars_leapmotor, 'https://cars.av.by/leapmotor'),
                 (page.btn_list_cars_lexus, 'https://cars.av.by/lexus'),
                 (page.btn_list_cars_lifan, 'https://cars.av.by/lifan'),
                 (page.btn_list_cars_lincoln, 'https://cars.av.by/lincoln'),
                 (page.btn_list_cars_livan, 'https://cars.av.by/livan'),
                 (page.btn_list_cars_lixiang, 'https://cars.av.by/lixiang'),
                 (page.btn_list_cars_lotus, 'https://cars.av.by/lotus'),
                 (page.btn_list_cars_lynk, 'https://cars.av.by/lynk-and-co'),
                 (page.btn_list_cars_hero, 'https://cars.av.by/m-hero'),
                 (page.btn_list_cars_maserati, 'https://cars.av.by/maserati'),
                 (page.btn_list_cars_mazda, 'https://cars.av.by/mazda'),
                 (page.btn_list_cars_benz, 'https://cars.av.by/mercedes-benz'),
                 (page.btn_list_cars_mercury, 'https://cars.av.by/mercury'),
                 (page.btn_list_cars_mg, 'https://cars.av.by/mg'),
                 (page.btn_list_cars_mini, 'https://cars.av.by/mini'),
                 (page.btn_list_cars_mitsubishi, 'https://cars.av.by/mitsubishi'),
                 (page.btn_list_cars_nio, 'https://cars.av.by/nio'),
                 (page.btn_list_cars_nissan, 'https://cars.av.by/nissan'),
                 (page.btn_list_cars_opel, 'https://cars.av.by/opel'),
                 (page.btn_list_cars_ora, 'https://cars.av.by/ora'),
                 (page.btn_list_cars_oting, 'https://cars.av.by/oting'),
                 (page.btn_list_cars_peugeot, 'https://cars.av.by/peugeot'),
                 (page.btn_list_cars_plymouth, 'https://cars.av.by/plymouth'),
                 (page.btn_list_cars_polar, 'https://cars.av.by/polar'),
                 (page.btn_list_cars_polestar, 'https://cars.av.by/polestar'),
                 (page.btn_list_cars_pontiac, 'https://cars.av.by/pontiac'),
                 (page.btn_list_cars_porsche, 'https://cars.av.by/porsche'),
                 (page.btn_list_cars_proton, 'https://cars.av.by/proton'),
                 (page.btn_list_cars_ram, 'https://cars.av.by/ram'),
                 (page.btn_list_cars_ravon, 'https://cars.av.by/ravon'),
                 (page.btn_list_cars_renault, 'https://cars.av.by/renault'),
                 (page.btn_list_cars_samsung, 'https://cars.av.by/renault-samsung'),
                 (page.btn_list_cars_rivian, 'https://cars.av.by/rivian'),
                 (page.btn_list_cars_roewe, 'https://cars.av.by/roewe'),
                 (page.btn_list_cars_royce, 'https://cars.av.by/rolls-royce'),
                 (page.btn_list_cars_rovers, 'https://cars.av.by/rover'),
                 (page.btn_list_cars_saab, 'https://cars.av.by/saab'),
                 (page.btn_list_cars_saipa, 'https://cars.av.by/saipa'),
                 (page.btn_list_cars_santana, 'https://cars.av.by/santana'),
                 (page.btn_list_cars_saturn, 'https://cars.av.by/saturn'),
                 (page.btn_list_cars_scion, 'https://cars.av.by/scion'),
                 (page.btn_list_cars_seat, 'https://cars.av.by/seat'),
                 (page.btn_list_cars_seres, 'https://cars.av.by/seres'),
                 (page.btn_list_cars_shenlan, 'https://cars.av.by/shenlan'),
                 (page.btn_list_cars_shineray, 'https://cars.av.by/shineray'),
                 (page.btn_list_cars_scoda, 'https://cars.av.by/skoda'),
                 (page.btn_list_cars_skywell, 'https://cars.av.by/skywell'),
                 (page.btn_list_cars_skyworth, 'https://cars.av.by/skyworth'),
                 (page.btn_list_cars_smart, 'https://cars.av.by/smart'),
                 (page.btn_list_cars_youn, 'https://cars.av.by/ssangyong'),
                 (page.btn_list_cars_stelato, 'https://cars.av.by/stelato'),
                 (page.btn_list_cars_subaru, 'https://cars.av.by/subaru'),
                 (page.btn_list_cars_suzuki, 'https://cars.av.by/suzuki'),
                 (page.btn_list_cars_tank, 'https://cars.av.by/tank'),
                 (page.btn_list_cars_tata, 'https://cars.av.by/tata'),
                 (page.btn_list_cars_tesla, 'https://cars.av.by/tesla'),
                 (page.btn_list_cars_think, 'https://cars.av.by/think'),
                 (page.btn_list_cars_toyota, 'https://cars.av.by/toyota'),
                 (page.btn_list_cars_trabant, 'https://cars.av.by/trabant'),
                 (page.btn_list_cars_venucia, 'https://cars.av.by/venucia'),
                 (page.btn_list_cars_vgv, 'https://cars.av.by/vgv'),
                 (page.btn_list_cars_volkswagen, 'https://cars.av.by/volkswagen'),
                 (page.btn_list_cars_volvo, 'https://cars.av.by/volvo'),
                 (page.btn_list_cars_vortex, 'https://cars.av.by/vortex'),
                 (page.btn_list_cars_voyah, 'https://cars.av.by/voyah'),
                 (page.btn_list_cars_wartburg, 'https://cars.av.by/wartburg'),
                 (page.btn_list_cars_weltmeister, 'https://cars.av.by/weltmeister'),
                 (page.btn_list_cars_wuling, 'https://cars.av.by/wuling'),
                 (page.btn_list_cars_xiaomi, 'https://cars.av.by/xiaomi'),
                 (page.btn_list_cars_xpeng, 'https://cars.av.by/xpeng'),
                 (page.btn_list_cars_zeekr, 'https://cars.av.by/zeekr'),
                 (page.btn_list_cars_zotye, 'https://cars.av.by/zotye'),
                 (page.btn_list_cars_zx, 'https://cars.av.by/zx'),
                 (page.btn_list_cars_bogdan, 'https://cars.av.by/bogdan'),
                 (page.btn_list_cars_gaz, 'https://cars.av.by/gaz'),
                 (page.btn_list_cars_zaz, 'https://cars.av.by/zaz'),
                 (page.btn_list_cars_izh, 'https://cars.av.by/izh'),
                 (page.btn_list_cars_lyaz, 'https://cars.av.by/luaz'),
                 (page.btn_list_cars_moskich, 'https://cars.av.by/moskvich'),
                 (page.btn_list_cars_raf, 'https://cars.av.by/raf'),
                 (page.btn_list_cars_tagaz, 'https://cars.av.by/tagaz'),
                 (page.btn_list_cars_yaz, 'https://cars.av.by/uaz'),
                 (page.btn_list_cars_exclusive, 'https://cars.av.by/eksklyuziv')]

    for cars, url_cars in cars_list:
        with allure.step("Проверка кликабельности"):
            check.is_true(cars.is_clickable())

        with allure.step("Проверка на наличие на экране элементов"):
            check.is_true(cars.is_visible())

        with allure.step("Тест проверки на правильный адрес кнопки"):
            check.equal(cars.get_attribute('href'), url_cars)

        with allure.step("Тест проверки -- на количество марок машин"):
            check.equal(page.list_of_cars.count(), 152)
